version: "3.8"

services:
  model:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rl_model_container
    ports:
      - "8888:8888"  
    volumes:
      - ./workspace:/workspace  
    environment:
      - NEPTUNE_PROJECT=<your_neptune_project>
      - NEPTUNE_API_TOKEN=<your_neptune_api_token>
    depends_on:
      - redis  
    networks:
      - redis_net

  redis:
    image: "redis:latest"  
    container_name: redis_db_container
    ports:
      - "6379:6379"  
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge

